AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ExistingQueueUrl:
    Type: String
    Description: URL da fila SQS existente

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app/main.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !Ref ExistingQueueUrl
