AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ExistingQueueUrl:
    Type: String
    Description: URL da fila SQS existente

  Stage:
    Type: String
    Description: Estágio do ambiente (dev, hml, prod)

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app/main.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !Ref ExistingQueueUrl

      Environment:
        Variables:
          DATABASE_HOST:
            Fn::If:
              - IsDev
              - "localhost"
              - Fn::If:
                  - IsHml
                  - "hml-db-host"
                  - Fn::If:
                      - IsProd
                      - "prod-db-host"
                      - "undefined"

          DATABASE_USER: "user"
          DATABASE_PASSWORD: "password"
          DATABASE_NAME: "mydatabase"

Conditions:
  IsDev: !Equals [!Ref Stage, "dev"]
  IsHml: !Equals [!Ref Stage, "hml"]
  IsProd: !Equals [!Ref Stage, "prod"]
